language: ruby
cache: bundler # caching to speed up dependency installation
rvm:
- 2.4.1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master
script:
  - echo "Starting build!"
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
  - echo "Finished build."
deploy:
  provider: pages
  local-dir: ./site
  target-branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
notifications:
  email: false