# Welcome to Jekyll-Doc-Theme!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jekyll Doc Theme
email: your-email@example.com
description: "Jekyll Template for Project Websites providing documentation and blog post pages."
baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog
url: "https://reinanhs.github.io/jekyll-doc-theme" # the base hostname & protocol for your site, e.g. http://example.com
repository: reinanhs/jekyll-doc-theme
twitter_username: ReinanGabriel9
github_username:  reinanhs

# Build settings
lang: en-US
encoding: utf-8
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - README.md

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true